
version: '3'

services:

  nginx:
    container_name: nginx

    build: ./requirements/nginx

    depends_on:
      - wordpress
    
    ports:
      - 443:443
    
    volumes:
      - wordpress_data:/var/www/html

    restart: always

    networks:
      - network

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
      
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on:
      - wordpress
    ports:
      - '6379:6379'
    restart:
      always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    ports:
      - "8000:8000"
    networks:
      - network
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/data/wordpress
      o: bind

networks:
  network:
    driver: bridge