
services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - asgard_net

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
    networks:
      - asgard_net

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    env_file:
      - .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html
    networks:
      - asgard_net
    

volumes:
  db_data:
    driver: local
    name: db_data
    driver_opts:
      type: none
      o: bind
      device: /home/mbaypara/data/mariadb
  wp_data:
    driver: local
    name: wp_data
    driver_opts:
      type: none
      o: bind
      device: /home/mbaypara/data/wordpress


networks:
  asgard_net:
    name: asgard_net
    driver: bridge